spring:
  application:
    name: Friend-Finder

  datasource:
    # تأكد إن الـ Service name عندك هو XEPDB1 فعلاً (لو مش متأكد جرب xe)
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: hr
    password: hr
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true

  main:
    banner-mode: "off"

server:
  port: 8080

logging:
  level:
    root: info

# إعدادات الـ JWT (أهم جزء)
#token:
  # يفضل تخبط ع الكيبورد وتكتب حروف كتير هنا عشان التشفير يبقى قوي
 # secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  #time: 86400000 # 24 hours in milliseconds (أسهل في التعامل)